# Generated by Django 2.1.3 on 2018-11-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('logo', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('Posting_title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('comp_name', models.CharField(max_length=30)),
                ('Internship_discription', models.TextField()),
                ('Location', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.PostType'),
        ),
    ]
